// File generated from our OpenAPI spec by Stainless.

package com.rain_sdk.api.models.applications.company

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.rain_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IssuingCompanyTest {

    @Test
    fun create() {
        val issuingCompany =
            IssuingCompany.builder()
                .applicationStatus(IssuingApplication.ApplicationStatus.APPROVED)
                .applicationCompletionLink(
                    IssuingApplication.ApplicationCompletionLink.builder()
                        .url("https://example.com")
                        .params(
                            IssuingApplication.ApplicationCompletionLink.Params.builder()
                                .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .build()
                )
                .applicationExternalVerificationLink(
                    IssuingApplication.ApplicationExternalVerificationLink.builder()
                        .url("https://example.com")
                        .params(
                            IssuingApplication.ApplicationExternalVerificationLink.Params.builder()
                                .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .build()
                )
                .applicationReason("applicationReason")
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .address(
                    PhysicalAddress.builder()
                        .city("city")
                        .country("country")
                        .countryCode("xx")
                        .line1("line1")
                        .postalCode("postalCode")
                        .region("region")
                        .line2("line2")
                        .build()
                )
                .name("name")
                .addUltimateBeneficialOwner(
                    IssuingCompany.UltimateBeneficialOwner.builder()
                        .applicationStatus(IssuingApplication.ApplicationStatus.APPROVED)
                        .applicationCompletionLink(
                            IssuingApplication.ApplicationCompletionLink.builder()
                                .url("https://example.com")
                                .params(
                                    IssuingApplication.ApplicationCompletionLink.Params.builder()
                                        .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .build()
                        )
                        .applicationExternalVerificationLink(
                            IssuingApplication.ApplicationExternalVerificationLink.builder()
                                .url("https://example.com")
                                .params(
                                    IssuingApplication.ApplicationExternalVerificationLink.Params
                                        .builder()
                                        .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .build()
                        )
                        .applicationReason("applicationReason")
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        assertThat(issuingCompany.applicationStatus())
            .isEqualTo(IssuingApplication.ApplicationStatus.APPROVED)
        assertThat(issuingCompany.applicationCompletionLink())
            .isEqualTo(
                IssuingApplication.ApplicationCompletionLink.builder()
                    .url("https://example.com")
                    .params(
                        IssuingApplication.ApplicationCompletionLink.Params.builder()
                            .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .build()
            )
        assertThat(issuingCompany.applicationExternalVerificationLink())
            .isEqualTo(
                IssuingApplication.ApplicationExternalVerificationLink.builder()
                    .url("https://example.com")
                    .params(
                        IssuingApplication.ApplicationExternalVerificationLink.Params.builder()
                            .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .build()
            )
        assertThat(issuingCompany.applicationReason()).isEqualTo("applicationReason")
        assertThat(issuingCompany.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(issuingCompany.address())
            .isEqualTo(
                PhysicalAddress.builder()
                    .city("city")
                    .country("country")
                    .countryCode("xx")
                    .line1("line1")
                    .postalCode("postalCode")
                    .region("region")
                    .line2("line2")
                    .build()
            )
        assertThat(issuingCompany.name()).isEqualTo("name")
        assertThat(issuingCompany.ultimateBeneficialOwners())
            .containsExactly(
                IssuingCompany.UltimateBeneficialOwner.builder()
                    .applicationStatus(IssuingApplication.ApplicationStatus.APPROVED)
                    .applicationCompletionLink(
                        IssuingApplication.ApplicationCompletionLink.builder()
                            .url("https://example.com")
                            .params(
                                IssuingApplication.ApplicationCompletionLink.Params.builder()
                                    .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .build()
                    )
                    .applicationExternalVerificationLink(
                        IssuingApplication.ApplicationExternalVerificationLink.builder()
                            .url("https://example.com")
                            .params(
                                IssuingApplication.ApplicationExternalVerificationLink.Params
                                    .builder()
                                    .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .build()
                    )
                    .applicationReason("applicationReason")
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val issuingCompany =
            IssuingCompany.builder()
                .applicationStatus(IssuingApplication.ApplicationStatus.APPROVED)
                .applicationCompletionLink(
                    IssuingApplication.ApplicationCompletionLink.builder()
                        .url("https://example.com")
                        .params(
                            IssuingApplication.ApplicationCompletionLink.Params.builder()
                                .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .build()
                )
                .applicationExternalVerificationLink(
                    IssuingApplication.ApplicationExternalVerificationLink.builder()
                        .url("https://example.com")
                        .params(
                            IssuingApplication.ApplicationExternalVerificationLink.Params.builder()
                                .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .build()
                )
                .applicationReason("applicationReason")
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .address(
                    PhysicalAddress.builder()
                        .city("city")
                        .country("country")
                        .countryCode("xx")
                        .line1("line1")
                        .postalCode("postalCode")
                        .region("region")
                        .line2("line2")
                        .build()
                )
                .name("name")
                .addUltimateBeneficialOwner(
                    IssuingCompany.UltimateBeneficialOwner.builder()
                        .applicationStatus(IssuingApplication.ApplicationStatus.APPROVED)
                        .applicationCompletionLink(
                            IssuingApplication.ApplicationCompletionLink.builder()
                                .url("https://example.com")
                                .params(
                                    IssuingApplication.ApplicationCompletionLink.Params.builder()
                                        .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .build()
                        )
                        .applicationExternalVerificationLink(
                            IssuingApplication.ApplicationExternalVerificationLink.builder()
                                .url("https://example.com")
                                .params(
                                    IssuingApplication.ApplicationExternalVerificationLink.Params
                                        .builder()
                                        .userId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .build()
                        )
                        .applicationReason("applicationReason")
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        val roundtrippedIssuingCompany =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(issuingCompany),
                jacksonTypeRef<IssuingCompany>(),
            )

        assertThat(roundtrippedIssuingCompany).isEqualTo(issuingCompany)
    }
}
